[package]
name = "DAY03"
version = "0.1.0"
authors = ["emrebadem_@hotmail.com <emrebadem_@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
